### ISSUE TITLE
Error: AttributeError: 'Text' object has no attribute 'set_pos'

### ISSUE THREAD

**Issue by besi** [umluizlima/dxf-ruler-generator#4]
Hello I wanted to give this script a shot and I ran in the following error:
 
Please note that I'm using Python3

    python3 --version
    Python 3.9.6

```
z ruler # go to my working directory
Successfully installed ezdxf-1.0.2 pyparsing-3.0.9 typing-extensions-4.5.0
WARNING: You are using pip version 21.2.4; however, version 23.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
➜  Ruler python3 -m dxf_ruler_generator 7

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/besi/Fablab/Ruler/dxf_ruler_generator.py", line 74, in <module>
    run()
  File "/Users/besi/Fablab/Ruler/dxf_ruler_generator.py", line 50, in run
    msp.add_text(
AttributeError: 'Text' object has no attribute 'set_pos'
```

**Comment by sugizo** [comment]
**env**
google colab
ubuntu jammy
Python 3.10.12

```
Traceback (most recent call last):
  File "/usr/local/bin/dxf-ruler-generator", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/dxf_ruler_generator.py", line 55, in run
    ).set_pos((x-1, args.width-tick_height))
AttributeError: 'Text' object has no attribute 'set_pos'
```

best regards

**Comment by sugizo** [comment]
with ezdxf latest version
update 
`set_pos`
with 
`set_placement`
in 
`dxf_ruler_generator.py`

solve the problem

best regards
